import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
 
export const metadata = {
  title: 'Theme Cloths',
  description: 'Generated by create next app',
  
}
export default function RootLayout({ children }) {
 
  return (
    <>
    
    <html lang="en">
    <link rel="icon" href="https://botw-pd.s3.amazonaws.com/onlineshopping.png" />
    
   
    <body className={inter.className}  >
  
      {children}
   
      </body>

      </html>
  
      </>
       
  )
}
 
 
 